### ISSUE TITLE
[Bug]: versions 1.7.21-1.7.23 are broken and should be yanked

### ISSUE THREAD

**Issue by sanderr** [mpenning/ciscoconfparse#277]
### What happened?

These versions don't have any dependencies and are therefore broken: the package does not work unless you manually install any required dependencies. Especially in automated environments this is infeasible.

I would like to suggest to yank these broken versions from PyPi.

### CiscoConfParse Version

1.7.21 - 1.7.23

### What Operating System are you using?

Linux - Debian, Ubuntu, CentOS, RHEL or others

### What Python version(s) have this problem?

Python 3.10, Python 3.9, Python 3.8, Python 3.7, Python 3.6

### Show us how to reproduce the problem.  Please tell us if the problem is specific to certain inputs or situations.

```python
`pip download ciscoconfparse==1.7.21` etc. It only downloads a single wheel, no dependencies. Installing it and use any functionality that requires a dependency will result in an exception.
```

### Python tracebacks

```shell
NA
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mpenning/ciscoconfparse/blob/main/CONTRIBUTING.md)

**Comment by sanderr** [comment]
Related to #276

**Comment by mpenning** [comment]
You have correctly identified a known packaging problem; however, manually installing dependencies works.  As such, I should not delete versions 1.7.21 through 1.7.23 from pypi.  Some people may have pinned those releases (and their copies work because they already installed dependencies).

**Comment by sanderr** [comment]
I agree the versions should not be deleted, but according to PyPi's documentation, yanking them results in the best of both worlds: when these versions are speciifically requested they will still be installed, but otherwise they will not be considered.

**Comment by mpenning** [comment]
> according to PyPi's documentation, yanking them re sults in the best of both worlds: when these versions are speciifically requested they will still be installed, but otherwise they will not be considered.

You have raised an interesting point, but we have already released 1.7.24 which is the de-facto release chosen unless someone pins it... I'm not sure yanking is value-add for status quo... if I'm wrong please tell me.

**Comment by sanderr** [comment]
I agree that the most important thing is that the de-facto release is not broken, so you've got the most common case covered. However, I still see three (admittedly rather rare) scenarios where this does not suffice:

1. Python 3.6. Fair enough if you consider this irrelevant, because 3.6 is end of life, but if you are still using it, the status quo for 3.6 is version `1.7.23`, which is one of the broken versions.
2. Direct constraint on this package: `pip download 'ciscoconfparse<1.7.24'` downloads the broken version `1.7.23`.
3. Conflicting dependencies: `pip` will always try to find a set of package versions for which all constraints are satisfied. This may mean looking back at older versions for a package. This package now has three versions that don't have any dependencies, therefore they can never conflict. Suppose you try to install this package together with some other package that has a conflicting constraint on e.g. `dnspython` (`ciscoconfparse-1.7.24` requires `dnspython>=2.1.0`). This would be equivalent to `pip download ciscoconfparse 'dnspython<2.2'`. If you run this you'll see that `pip` rejects `1.7.24` because of the conflict, then selects and downloads the broken `1.7.23`.

I think scenarios 1 and 3 are the most realistic to occur in practice. That said, as you already mentioned, for the common case there is no issue. I therefore don't feel too strongly about this, but I do still think it's good practice to yank such versions so that they can never be installed by accident.

**Comment by FliesLikeABrick** [comment]
Please yank 1.7.21 as well.  We are on python3.6 for the next few months and in our latest deployment we ended up with 1.7.21.  We had to manually revert to 1.7.20 to fix the issue but would like to remove that version lock so that we don't have tech debt when we get on newer python later this year.

**Comment by mpenning** [comment]
I yanked 1.7.21

On Wed, Jul 12, 2023 at 16:18 FliesLikeABrick ***@***.***>
wrote:

> Please yank 1.7.21 as well. We are on python3.6 for the next few months
> and in our latest deployment we ended up with 1.7.21. We had to manually
> revert to 1.7.20 to fix the issue but would like to remove that version
> lock so that we don't have tech debt when we get on newer python later this
> year.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>
-- 
Kind Regards,
\mike

LinkedIn - https://www.linkedin.com/in/mikepenn/
